version: '3.1'

services:
  my_api:
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: my_mongo
    image: mongo
    ports:
      - '27017:27017'
    logging:
      driver: none
